{% set version = '0.5.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sps/sps_{{ version }}.tar.gz
  sha256: 2a0862338f2326128ab21ded3c590730c29758916c2b61984eafaabb97f486a4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sps')"           # [not win]
    - "\"%R%\" -e \"library('sps')\""  # [win]

about:
  home: https://marberts.github.io/sps/, https://github.com/marberts/sps
  license: MIT
  summary: "Sequential Poisson sampling is a variation of Poisson sampling for drawing probability-proportional-to-size
    samples with a given number of units, and is commonly used for price-index surveys.
    This package gives functions to draw stratified sequential Poisson samples according
    to the method by Ohlsson (1998, ISSN:0282-423X), as well as other order sample designs
    by Rosen (1997, <doi:10.1016/S0378-3758(96)00186-3>), and generate appropriate
    bootstrap replicate weights according to the generalized bootstrap method by Beaumont
    and Patak (2012, <doi:10.1111/j.1751-5823.2011.00166.x>)."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - marberts

# Package: sps
# Title: Sequential Poisson Sampling
# Version: 0.5.3
# Authors@R: c( person("Steve", "Martin", role = c("aut", "cre", "cph"), email = "stevemartin041@gmail.com", comment = c(ORCID = "0000-0003-2544-9480")), person("Justin", "Francis", role = "ctb") )
# Description: Sequential Poisson sampling is a variation of Poisson sampling for drawing probability-proportional-to-size samples with a given number of units, and is commonly used for price-index surveys. This package gives functions to draw stratified sequential Poisson samples according to the method by Ohlsson (1998, ISSN:0282-423X), as well as other order sample designs by Rosen (1997, <doi:10.1016/S0378-3758(96)00186-3>), and generate appropriate bootstrap replicate weights according to the generalized bootstrap method by Beaumont and Patak (2012, <doi:10.1111/j.1751-5823.2011.00166.x>).
# Depends: R (>= 4.0)
# Imports: stats
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0)
# Config/testthat/edition: 3
# License: MIT + file LICENSE
# Encoding: UTF-8
# URL: https://marberts.github.io/sps/, https://github.com/marberts/sps
# BugReports: https://github.com/marberts/sps/issues
# VignetteBuilder: knitr
# RoxygenNote: 7.2.3
# NeedsCompilation: no
# Packaged: 2023-10-16 02:47:03 UTC; steve
# Author: Steve Martin [aut, cre, cph] (<https://orcid.org/0000-0003-2544-9480>), Justin Francis [ctb]
# Maintainer: Steve Martin <stevemartin041@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-10-16 04:30:02 UTC
